name: Family Circle Farm
favicon: null
layout_spectrum: 0.26389
typography_spectrum: 0.2479633465409279
title: Family Circle Farm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
