name: Family Circle Farm
favicon: null
layout_spectrum: 0.20589907024987042
typography_spectrum: 0.2479633465409279
title: Family Circle Farm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6911112882662565
  lightness: 0.6205886057578027
  saturation: 0.1565050296485424
  rhythmicContrast: 0.7600927003659308
purpose: []
